### ISSUE TITLE
'Undefined array key "height"' error when only width is passed to getImageUrl()

### ISSUE THREAD

**Issue by aelvan** [vaersaagod/muxmate#1]
![CleanShot 2023-06-23 at 09 46 00](https://github.com/vaersaagod/muxmate/assets/2675644/8ad18ddc-650a-4193-b8a5-b4148606f2a4)

**Comment by aelvan** [comment]
Didn't expect there to be bugs. Disappointed.

**Comment by mmikkel** [comment]
@aelvan Thanks for reporting that!

Fixed in version 1.1.3. FFR, let's try to keep our emotions out of this.
