### ISSUE TITLE
Craft 5 support

### ISSUE THREAD

**Issue by plcdnl** [vaersaagod/muxmate#2]
Hi!
Just checking. Is Craft 5 support on your roadmap? 

Thanks!

**Comment by plcdnl** [comment]
https://github.com/vaersaagod/muxmate/pull/3

Just pushed a pull request here

**Comment by mmikkel** [comment]
Hi @plcdnl, thanks for contributing.

MuxMate is a internal plugin (i.e. not listed on the plugin store), and a Craft 5 version isn't a priority for us right now.

**Comment by plcdnl** [comment]
Thank you very much, unfortunately I didn't understand initially, sorry for the inconvenience!

**Comment by mmikkel** [comment]
@plcdnl No worries at all 😄
